### POST request to process commands
POST http://localhost:5000/api/rovers/commands
Content-Type: application/json

{
  "position": {
    "x": 3,
    "y": 3,
    "direction": "E"
  },
  "commands": "MRRMMRMRRM"
}

###

POST http://localhost:5000/api/rovers/register
Content-Type: application/json

{
  "email": "alexandre@gmail.com",
  "password": "123456789"
}