### POST request to process commands
POST http://localhost:5000/api/rovers/commands  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQyMzQ4NTY1ZWE2NjY5MTU3MjM0Y2UiLCJpYXQiOjE3MzI0Mzg0MzMsImV4cCI6MTczMjQ0MjAzM30.M1eARO-H6dnC9ASTL0r5FR2WMP24WWtRNHZHlWaDbXE
 //Authorization Bearer <Token> the token depends on the user generate the token by login in the system.
{
  "position": {
    "x": 1,
    "y": 0,
    "direction": "E"
  },
  "commands": "MRRMMRMRRM"
}

###

POST http://localhost:5000/api/rovers/register
Content-Type: application/json
//Register to have a valid account
{
  "email": "user12@example.com",
  "password": "SecureP@ssw0rd"
}

###

POST http://localhost:5000/api/rovers/login
Content-Type: application/json
//Login to generate your individual Authorization Bearer <Token>
{
  "email": "user@example.com",
  "password": "SecureP@ssw0rd"
}

###

GET http://localhost:5000/api/rovers/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQyMzQ4NTY1ZWE2NjY5MTU3MjM0Y2UiLCJpYXQiOjE3MzI0Mzg0MzMsImV4cCI6MTczMjQ0MjAzM30.M1eARO-H6dnC9ASTL0r5FR2WMP24WWtRNHZHlWaDbXE
//Use your Authorization Bearer <Token> to access commands history or to make new commands.
{
  "email": "user@example.com",
  "password": "SecureP@ssw0rd"
}
